Add Styling on the react project
BonkeGcobo/BookStore2 pull request #7
Opened 2022-04-01 18:29 UTC by BonkeGcobo

Adding Styling on the project

2022-04-01 19:08 UTC, AshakaE requested changes
Hi @BonkeGcobo , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

- [x] Please note that styling is exactly the same as the one in the [Zeplin template](https://app.zeplin.io/project/5b35a9e13227086040f8eb75/screen/5b695e29bb8c844f118f9378), that includes (fonts face, font size and spacing)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-01 19:08 UTC, AshakaE commented on src/components/Books/ProgressBar.js
> +        >
- [ ] Please note that inline styling is not allowed for this project

2022-04-02 17:33 UTC, Mihndim2020 approved these changes
# STATUS: APPROVED!!!  🎉 🎉 🎉 :champagne: :champagne: :champagne:
Hi @BonkeG, 

Your project is complete! Great work on making the changes requested by the previous reviewer. There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉 🎉 :champagne: :champagne: :champagne:

![Congratulations-Memes-FEATURED](https://user-images.githubusercontent.com/65852621/133696300-b506e476-dc1a-443e-935a-c6f434e788b6.jpg)

## Optional suggestions

_Check the comments under the review._

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-02 17:33 UTC, Mihndim2020 commented on src/components/Books/ProgressBar.js
> +          }}
- [OPTIONAL] As requested by the previous code reviewer, please kindly define these styles in a different file and import them in to this component, for inline styling is not a best practice.

2022-04-02 17:33 UTC, Mihndim2020 commented on src/components/Books/ProgressBar.js
> +            })}
- [OPTIONAL] As requested by the previous code reviewer, please kindly define these styles in a different file and import them in to this component, for inline styling is not a best practice.

2022-04-02 17:43 UTC, merged